// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: api/gateway/v1/share.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareStatus int32

const (
	ShareStatus_undefined ShareStatus = 0
	ShareStatus_pending   ShareStatus = 1
	ShareStatus_accepted  ShareStatus = 2
	ShareStatus_rejected  ShareStatus = 3
)

// Enum value maps for ShareStatus.
var (
	ShareStatus_name = map[int32]string{
		0: "undefined",
		1: "pending",
		2: "accepted",
		3: "rejected",
	}
	ShareStatus_value = map[string]int32{
		"undefined": 0,
		"pending":   1,
		"accepted":  2,
		"rejected":  3,
	}
)

func (x ShareStatus) Enum() *ShareStatus {
	p := new(ShareStatus)
	*p = x
	return p
}

func (x ShareStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShareStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gateway_v1_share_proto_enumTypes[0].Descriptor()
}

func (ShareStatus) Type() protoreflect.EnumType {
	return &file_api_gateway_v1_share_proto_enumTypes[0]
}

func (x ShareStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShareStatus.Descriptor instead.
func (ShareStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{0}
}

type GetShareListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetShareListReq) Reset() {
	*x = GetShareListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShareListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareListReq) ProtoMessage() {}

func (x *GetShareListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareListReq.ProtoReflect.Descriptor instead.
func (*GetShareListReq) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{0}
}

type GetShareListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerShares     []*GetShareListReply_ShareInfo `protobuf:"bytes,1,rep,name=owner_shares,json=ownerShares,proto3" json:"owner_shares,omitempty"`               // 自己分享的
	FromOtherShares []*GetShareListReply_ShareInfo `protobuf:"bytes,2,rep,name=from_other_shares,json=fromOtherShares,proto3" json:"from_other_shares,omitempty"` // 其他人分享的
}

func (x *GetShareListReply) Reset() {
	*x = GetShareListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShareListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareListReply) ProtoMessage() {}

func (x *GetShareListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareListReply.ProtoReflect.Descriptor instead.
func (*GetShareListReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{1}
}

func (x *GetShareListReply) GetOwnerShares() []*GetShareListReply_ShareInfo {
	if x != nil {
		return x.OwnerShares
	}
	return nil
}

func (x *GetShareListReply) GetFromOtherShares() []*GetShareListReply_ShareInfo {
	if x != nil {
		return x.FromOtherShares
	}
	return nil
}

type ShareInviteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCode string `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"` // 用户id
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备id
}

func (x *ShareInviteReq) Reset() {
	*x = ShareInviteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareInviteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareInviteReq) ProtoMessage() {}

func (x *ShareInviteReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareInviteReq.ProtoReflect.Descriptor instead.
func (*ShareInviteReq) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{2}
}

func (x *ShareInviteReq) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *ShareInviteReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ShareInviteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShareInviteReply) Reset() {
	*x = ShareInviteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareInviteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareInviteReply) ProtoMessage() {}

func (x *ShareInviteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareInviteReply.ProtoReflect.Descriptor instead.
func (*ShareInviteReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{3}
}

type ShareConfirmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareId int64 `protobuf:"varint,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"` // 分享id
	Confirm bool  `protobuf:"varint,2,opt,name=confirm,proto3" json:"confirm,omitempty"`                // 是否同意
}

func (x *ShareConfirmReq) Reset() {
	*x = ShareConfirmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareConfirmReq) ProtoMessage() {}

func (x *ShareConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareConfirmReq.ProtoReflect.Descriptor instead.
func (*ShareConfirmReq) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{4}
}

func (x *ShareConfirmReq) GetShareId() int64 {
	if x != nil {
		return x.ShareId
	}
	return 0
}

func (x *ShareConfirmReq) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type ShareConfirmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShareConfirmReply) Reset() {
	*x = ShareConfirmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareConfirmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareConfirmReply) ProtoMessage() {}

func (x *ShareConfirmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareConfirmReply.ProtoReflect.Descriptor instead.
func (*ShareConfirmReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{5}
}

type ShareRevokeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareId int64 `protobuf:"varint,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"` // 分享id
}

func (x *ShareRevokeReq) Reset() {
	*x = ShareRevokeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareRevokeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRevokeReq) ProtoMessage() {}

func (x *ShareRevokeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRevokeReq.ProtoReflect.Descriptor instead.
func (*ShareRevokeReq) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{6}
}

func (x *ShareRevokeReq) GetShareId() int64 {
	if x != nil {
		return x.ShareId
	}
	return 0
}

type ShareRevokeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShareRevokeReply) Reset() {
	*x = ShareRevokeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareRevokeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareRevokeReply) ProtoMessage() {}

func (x *ShareRevokeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareRevokeReply.ProtoReflect.Descriptor instead.
func (*ShareRevokeReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{7}
}

type ShareExitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShareId int64 `protobuf:"varint,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"` // 分享id
}

func (x *ShareExitReq) Reset() {
	*x = ShareExitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareExitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareExitReq) ProtoMessage() {}

func (x *ShareExitReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareExitReq.ProtoReflect.Descriptor instead.
func (*ShareExitReq) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{8}
}

func (x *ShareExitReq) GetShareId() int64 {
	if x != nil {
		return x.ShareId
	}
	return 0
}

type ShareExitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShareExitReply) Reset() {
	*x = ShareExitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareExitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareExitReply) ProtoMessage() {}

func (x *ShareExitReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareExitReply.ProtoReflect.Descriptor instead.
func (*ShareExitReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{9}
}

type GetShareListReply_ShareInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserCode    string      `protobuf:"bytes,2,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	DeviceId    string      `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName  string      `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	UserName    string      `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ShareStatus ShareStatus `protobuf:"varint,6,opt,name=share_status,json=shareStatus,proto3,enum=api.gateway.v1.ShareStatus" json:"share_status,omitempty"`
}

func (x *GetShareListReply_ShareInfo) Reset() {
	*x = GetShareListReply_ShareInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_gateway_v1_share_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShareListReply_ShareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareListReply_ShareInfo) ProtoMessage() {}

func (x *GetShareListReply_ShareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_share_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareListReply_ShareInfo.ProtoReflect.Descriptor instead.
func (*GetShareListReply_ShareInfo) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_share_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetShareListReply_ShareInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetShareListReply_ShareInfo) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *GetShareListReply_ShareInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetShareListReply_ShareInfo) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GetShareListReply_ShareInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetShareListReply_ShareInfo) GetShareStatus() ShareStatus {
	if x != nil {
		return x.ShareStatus
	}
	return ShareStatus_undefined
}

var File_api_gateway_v1_share_proto protoreflect.FileDescriptor

var file_api_gateway_v1_share_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x92, 0x03, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0c,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x57, 0x0a, 0x11,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x73, 0x1a, 0xd3, 0x01, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5c, 0x0a, 0x0e, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4f, 0x0a,
	0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x22, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x07, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x13,
	0x0a, 0x11, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x34, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x76, 0x6f,
	0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00,
	0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x65, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x32, 0x0a,
	0x0c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a,
	0x08, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x07, 0x73, 0x68, 0x61, 0x72, 0x65, 0x49,
	0x64, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2a, 0x45, 0x0a, 0x0b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x03, 0x32, 0xa2, 0x04, 0x0a, 0x05, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x12, 0x6b, 0x0a, 0x0b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x3a, 0x01, 0x2a,
	0x22, 0x0f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x12, 0x6f, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52,
	0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a,
	0x22, 0x10, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x12, 0x6b, 0x0a, 0x0b, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x76, 0x6f, 0x6b,
	0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x3a, 0x01, 0x2a, 0x22, 0x0f,
	0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x12,
	0x63, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x45, 0x78, 0x69, 0x74, 0x12, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f,
	0x65, 0x78, 0x69, 0x74, 0x12, 0x69, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f,
	0x12, 0x0d, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42,
	0x43, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x72, 0x65, 0x65, 0x77, 0x75, 0x2f, 0x70, 0x68, 0x69, 0x63, 0x6f, 0x6d, 0x6d, 0x5f, 0x64,
	0x63, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gateway_v1_share_proto_rawDescOnce sync.Once
	file_api_gateway_v1_share_proto_rawDescData = file_api_gateway_v1_share_proto_rawDesc
)

func file_api_gateway_v1_share_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_share_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gateway_v1_share_proto_rawDescData)
	})
	return file_api_gateway_v1_share_proto_rawDescData
}

var file_api_gateway_v1_share_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gateway_v1_share_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_gateway_v1_share_proto_goTypes = []interface{}{
	(ShareStatus)(0),                    // 0: api.gateway.v1.ShareStatus
	(*GetShareListReq)(nil),             // 1: api.gateway.v1.GetShareListReq
	(*GetShareListReply)(nil),           // 2: api.gateway.v1.GetShareListReply
	(*ShareInviteReq)(nil),              // 3: api.gateway.v1.ShareInviteReq
	(*ShareInviteReply)(nil),            // 4: api.gateway.v1.ShareInviteReply
	(*ShareConfirmReq)(nil),             // 5: api.gateway.v1.ShareConfirmReq
	(*ShareConfirmReply)(nil),           // 6: api.gateway.v1.ShareConfirmReply
	(*ShareRevokeReq)(nil),              // 7: api.gateway.v1.ShareRevokeReq
	(*ShareRevokeReply)(nil),            // 8: api.gateway.v1.ShareRevokeReply
	(*ShareExitReq)(nil),                // 9: api.gateway.v1.ShareExitReq
	(*ShareExitReply)(nil),              // 10: api.gateway.v1.ShareExitReply
	(*GetShareListReply_ShareInfo)(nil), // 11: api.gateway.v1.GetShareListReply.ShareInfo
}
var file_api_gateway_v1_share_proto_depIdxs = []int32{
	11, // 0: api.gateway.v1.GetShareListReply.owner_shares:type_name -> api.gateway.v1.GetShareListReply.ShareInfo
	11, // 1: api.gateway.v1.GetShareListReply.from_other_shares:type_name -> api.gateway.v1.GetShareListReply.ShareInfo
	0,  // 2: api.gateway.v1.GetShareListReply.ShareInfo.share_status:type_name -> api.gateway.v1.ShareStatus
	3,  // 3: api.gateway.v1.Share.ShareInvite:input_type -> api.gateway.v1.ShareInviteReq
	5,  // 4: api.gateway.v1.Share.ShareConfirm:input_type -> api.gateway.v1.ShareConfirmReq
	7,  // 5: api.gateway.v1.Share.ShareRevoke:input_type -> api.gateway.v1.ShareRevokeReq
	9,  // 6: api.gateway.v1.Share.ShareExit:input_type -> api.gateway.v1.ShareExitReq
	1,  // 7: api.gateway.v1.Share.GetShareList:input_type -> api.gateway.v1.GetShareListReq
	4,  // 8: api.gateway.v1.Share.ShareInvite:output_type -> api.gateway.v1.ShareInviteReply
	6,  // 9: api.gateway.v1.Share.ShareConfirm:output_type -> api.gateway.v1.ShareConfirmReply
	8,  // 10: api.gateway.v1.Share.ShareRevoke:output_type -> api.gateway.v1.ShareRevokeReply
	10, // 11: api.gateway.v1.Share.ShareExit:output_type -> api.gateway.v1.ShareExitReply
	2,  // 12: api.gateway.v1.Share.GetShareList:output_type -> api.gateway.v1.GetShareListReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_share_proto_init() }
func file_api_gateway_v1_share_proto_init() {
	if File_api_gateway_v1_share_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_gateway_v1_share_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShareListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShareListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareInviteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareInviteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareConfirmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareConfirmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareRevokeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareRevokeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareExitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareExitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_gateway_v1_share_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShareListReply_ShareInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gateway_v1_share_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_share_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_share_proto_depIdxs,
		EnumInfos:         file_api_gateway_v1_share_proto_enumTypes,
		MessageInfos:      file_api_gateway_v1_share_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_share_proto = out.File
	file_api_gateway_v1_share_proto_rawDesc = nil
	file_api_gateway_v1_share_proto_goTypes = nil
	file_api_gateway_v1_share_proto_depIdxs = nil
}
