server:
  http:
    addr: 0.0.0.0:8002
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:123456@tcp(localhost:3306)/dc1?charset=utf8&parseTime=true
  redis:
    addr: localhost:6379
    password: password
    read_timeout: 1s
    write_timeout: 1s
    db: 1
  sqlite3:
    addr: data.db
  wechat:
    secret_key: qwertyuiop
    token_ttl: 2592000s
    device_flush_interval: 5s
    online_interval: 60s
    plan_count: 5
    host: 127.0.0.1
    miniapps:
      wx_XXXX: ##  小程序ID
        app_id: wx_XXXX
        app_secret: xxxxxxx

